branches:
  only:
  - master

language: rust

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

sudo: false

# Dependencies of kcov, used for cargo-travis
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libbz2-dev
      - binutils-dev
      - libiberty-dev
      - cmake
      - musl
      - musl-dev
      - musl-tools
    sources:
      - kalakris-cmake

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup component add rustfmt-preview
  - rustup target add x86_64-unknown-linux-musl

script:
  #- cargo fmt --version
  #- cargo fmt -- --check
  - cargo build --all-features
  - cargo test --all-features
  - cargo build --no-default-features
  - cargo test --no-default-features
  - cargo build --target x86_64-unknown-linux-musl --all-features
  - cargo test --target x86_64-unknown-linux-musl --all-features
  - cargo build --target x86_64-unknown-linux-musl --no-default-features
  - cargo test --target x86_64-unknown-linux-musl --no-default-features

env:
  global:
    - RUST_BACKTRACE=1
